FIND_PATH(LAZY_INCLUDE_DIR *.h ${CMAKE_CURRENT_SOURCE_DIR}/include)
FIND_LIBRARY(LAZY_LIBRARY *.so ${CMAKE_CURRENT_SOURCE_DIR}/lib)

SET(LAZY_FOUND FALSE)
if (LAZY_INCLUDE_DIR AND LAZY_LIBRARY)
  SET(LAZY_FOUND TRUE)
endif()
